export const blogsData = [
    {
        id: 1,
        img: "/article-1.png",
        title: "7 ways to decor your home like a professional",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 2,
        img: "/article-2.png",
        title: "Inside a beautiful kitchen organization",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 3,
        img: "/article-3.png",
        title: "Decor your bedroom for your children",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 4,
        img: "/article-1.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 5,
        img: "/article-3.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 6,
        img: "/article-2.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 7,
        img: "/article-2.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 8,
        img: "/article-1.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 9,
        img: "/article-3.png",
        title: "Modern texas home is beautiful and completely kid-friendly",
        date: "October 16, 2023",
        timestamp: new Date("2023-10-16").getTime(),
    },
    {
        id: 10,
        img: "/article-1.png",
        title: "Color pallettes for ultimate relaxation",
        date: "October 17, 2023",
        timestamp: new Date("2023-10-17").getTime(),
    },
    {
        id: 11,
        img: "/article-2.png",
        title: "Lighting fixtures to make your modern space pop",
        date: "October 18, 2023",
        timestamp: new Date("2023-10-18").getTime(),
    },
    {
        id: 12,
        img: "/article-3.png",
        title: "How to safely secure furniture around toddlers",
        date: "October 19, 2023",
        timestamp: new Date("2023-10-19").getTime(),
    },
];